name: Actualización Automática de Catálogo

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  actualizar-datos:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Ejecutar Script de Actualización
        run: node scripts/obtenerEstrenos.js
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}

      - name: Guardar y subir cambios a GitHub
        run: |
          git config --global user.name "Streaming Bot"
          git config --global user.email "bot@tusitio.com"

          git add data/estrenos.json

          git diff --cached --quiet && echo "Sin cambios" && exit 0

          git commit -m "Actualización automática de estrenos"

          git push
